name = "Garden MC [BMC6 Fork]"
version = "v1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1947131e67e742ae600520115d15c6fd26444977ec36386854dc8d37927e0f65"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.100"

[options]
datapack-folder = "config/paxi/datapacks"
