name = "Garden MC [BMC6 Fork]"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "152a0a41ac017e42e2f2c8913f0b705691c68392ae78a8281f36768fd33e5100"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.97"
