name = "Garden MC [BMC6 Fork]"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a13f34e0ecd1e1f3a9b864f11ca74563e11afd4d04f985bcea92cdf13c968bb"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.93"
